# Generated by Django 6.0.5 on 2026-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottoDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True)),
                ('winning_number1', models.PositiveSmallIntegerField()),
                ('winning_number2', models.PositiveSmallIntegerField()),
                ('winning_number3', models.PositiveSmallIntegerField()),
                ('winning_number4', models.PositiveSmallIntegerField()),
                ('winning_number5', models.PositiveSmallIntegerField()),
                ('winning_number6', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LottoryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('purchase_type', models.CharField(choices=[('manual', '수동'), ('auto', '자동')], default='manual', max_length=10)),
                ('number1', models.PositiveSmallIntegerField()),
                ('number2', models.PositiveSmallIntegerField()),
                ('number3', models.PositiveSmallIntegerField()),
                ('number4', models.PositiveSmallIntegerField()),
                ('number5', models.PositiveSmallIntegerField()),
                ('number6', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
