# Generated by Django 6.0.5 on 2026-05-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LottoryTicket',
            new_name='LotteryTicket',
        ),
    ]
